language: node_js
node_js: node
deploy: app: salty-lowlands-25139
  provider: heroku
  api_key:
    secure: PffLAM6RC5GaNl7cvAsHeLD+wfLKh4RdKERXwxOpLwALDdnFLUmdMUVDVNKP9qeFTbqKJNT76jPkILXR0OsxDIgX64KEuyPTzQyqlA29fgyx409JXuOUXVyVWy5lZimXJwD9XyxIv83kVEqExaKNOY+/ThvLNSeujzusWcB/tBO6E+4cWVdUUpoNr+N0Kb89Herqz5b8pPqVsF9uAMSjLeVMvs9XPOQ9PHsGrryWEe2ObvBHs2LZZA+szmINvdKcbxgnJFwy1q1fK+xeh4OhfgMk415EszVnc7oSrD81DJREQjDuIVilADF4rNRopF6yrqiNDC45Mwmu8SveQ6u77wMCT8fpuc/X02mW1/qOWWaVKOT9XKuJ6pRMYQ56fqAwFQQhgySe1c/WToZB2pzl91qJhDBzXT8kJdJRH9UgLTBuUmGNRrHWZ09lOim/LwMENYnq5OM7818u9kcHqL+uu/pgEfm30vM89gXVtj0YLg1EjebV+dr+7u/a9C4vwL7xdrrHp2HAUtctgGZYn6eVsZ+b+kV23T0IwSa0hgHxUsEoMTV150PXtSL959CObgeJkusTxkbxZ5W78KWQOAkOPPgdDzrDgI1g4z09EUmDRZtayycaa0c7ClW1SOAXtCbihBrcRQYbUf3gy6rmPXNSG1ONuQTwUrHbfZh+yVVPGCE=
  app: git diff
  on:
    repo: mscottcam/node-shopping-list-integration-tests
    branch: test-for-recipes
